version: '3.9'

services:
  database:
    image: postgres:15.6
    restart: always
    env_file: db.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

# Para acceder
# psql -U geoglows -d geoglows -h localhost -p 5433
